package com.craftworks.music.managers.audio

/**
 * Inter-band crosstalk compensation for the 10-band equalizer.
 *
 * Cascading peaking biquads at 1-octave spacing do not sum linearly: each
 * band's filter also boosts (or, in cuts, attenuates) its neighbors' center
 * frequencies, so a naive cascade overshoots the requested curve. This file
 * precomputes the inverse of the 10x10 coupling matrix and applies it at
 * control rate: the per-biquad target gains become `M^-1 * userGains`, which
 * cancels the inter-band interference and makes the measured response match
 * the user's requested gains at every band center.
 *
 * The inverse matrix is a compile-time constant because every parameter it
 * depends on is fixed for the app's life: the 10 center frequencies of
 * [EQ_BAND_FREQUENCIES_HZ] (31 Hz .. 16 kHz), the peaking Q of sqrt(2f)
 * (~1.414), and the nominal 44100 Hz reference sample rate. If any of those
 * change, the matrix must be regenerated by the same procedure described in
 * [INVERSE_COUPLING_MATRIX].
 *
 * This object is pure Kotlin math with no Android or Media3 dependencies.
 */
object EqualizerCouplingMatrix {

    /**
     * Reference sample rate the coupling matrix was computed for. The equalizer
     * runs at the device's actual rate (typically 44100 or 48000 Hz); the small
     * mismatch is negligible at the band widths involved and keeps the matrix a
     * compile-time constant, as the reference design intends.
     */
    const val REFERENCE_SAMPLE_RATE_HZ = 44100f

    /**
     * 10x10 inverse coupling matrix, row-major over [EQ_BAND_FREQUENCIES_HZ]
     * order. Entry `[i][j]` is the compensation applied to band `i`'s gain when
     * band `j` requests 1 dB, so `compensated = INVERSE_COUPLING_MATRIX * user`.
     *
     * Generation (done once with a plain-JVM tool, not at runtime):
     *  1. For each band j, design a peaking biquad at its center frequency with
     *     a 1 dB probe gain (RBJ formulas, Q = sqrt(2), fs = 44100).
     *  2. Sample |H(e^jw)| of that filter at every band center i and store
     *     `M[i][j] = 20*log10(|H|)`; the diagonal is exactly 1.0, off-diagonal
     *     entries are the crosstalk.
     *  3. Invert M (Gauss-Jordan with partial pivoting; M is diagonally
     *     dominant and non-singular, so the inverse equals the pseudo-inverse
     *     used by the reference implementation).
     */
    val INVERSE_COUPLING_MATRIX: Array<FloatArray> = arrayOf(
        floatArrayOf(
            1.0313324f, -0.17947122f, -0.0011783964f, -0.0015964994f, -1.9772572E-4f,
            -3.670261E-5f, -5.984755E-6f, -9.933173E-7f, -1.4842763E-7f, -1.0118074E-8f,
        ),
        floatArrayOf(
            -0.17947122f, 1.0670792f, -0.19225697f, -6.5221044E-4f, -0.0015757829f,
            -1.9094118E-4f, -3.5547942E-5f, -5.686473E-6f, -8.580338E-7f, -5.8340195E-8f,
        ),
        floatArrayOf(
            -0.0011783964f, -0.19225697f, 1.0700195f, -0.18779734f, -7.701096E-4f,
            -0.0015502854f, -1.8846402E-4f, -3.431019E-5f, -5.0063095E-6f, -3.42737E-7f,
        ),
        floatArrayOf(
            -0.0015964994f, -6.5221044E-4f, -0.18779734f, 1.0683789f, -0.18764266f,
            -8.053769E-4f, -0.0015382059f, -1.853083E-4f, -3.038362E-5f, -2.0314533E-6f,
        ),
        floatArrayOf(
            -1.9772572E-4f, -0.0015757829f, -7.701096E-4f, -0.18764266f, 1.0681492f,
            -0.18710628f, -9.041539E-4f, -0.0014857391f, -1.6756456E-4f, -1.2163888E-5f,
        ),
        floatArrayOf(
            -3.670261E-5f, -1.9094118E-4f, -0.0015502854f, -8.053769E-4f, -0.18710628f,
            1.0672364f, -0.1849753f, -0.0012693714f, -0.0012709957f, -7.069918E-5f,
        ),
        floatArrayOf(
            -5.984755E-6f, -3.5547942E-5f, -1.8846402E-4f, -0.0015382059f, -9.041539E-4f,
            -0.1849753f, 1.0637047f, -0.17665128f, -0.0022936687f, -4.701665E-4f,
        ),
        floatArrayOf(
            -9.933173E-7f, -5.686473E-6f, -3.431019E-5f, -1.853083E-4f, -0.0014857391f,
            -0.0012693714f, -0.17665128f, 1.0513388f, -0.14570577f, -0.0022084848f,
        ),
        floatArrayOf(
            -1.4842763E-7f, -8.580338E-7f, -5.0063095E-6f, -3.038362E-5f, -1.6756456E-4f,
            -0.0012709957f, -0.0022936687f, -0.14570577f, 1.0233911f, -0.04937302f,
        ),
        floatArrayOf(
            -1.0118074E-8f, -5.83402E-8f, -3.42737E-7f, -2.0314533E-6f, -1.2163888E-5f,
            -7.069918E-5f, -4.701665E-4f, -0.0022084848f, -0.04937302f, 1.0024697f,
        ),
    )

    /**
     * Computes `INVERSE_COUPLING_MATRIX * [targets]` and stores the result in
     * [into]. Both arrays must have 10 elements. Allocation-free, so it is safe
     * to call from control-rate code; the audio-rate path never touches this.
     */
    fun compensatedGains(targets: FloatArray, into: FloatArray) {
        var i = 0
        while (i < 10) {
            val row = INVERSE_COUPLING_MATRIX[i]
            var acc = 0f
            var j = 0
            while (j < 10) {
                acc += row[j] * targets[j]
                j++
            }
            into[i] = acc
            i++
        }
    }
}
